essai/urls.py
from django.urls import path

from . import views


"""
urls.py nous permet de lier la vue avec une url
path('Donné en arg', view.NomDeLaVue, name='NomDeLaVue'),

"""


urlpatterns = [
    path('', views.index, name='index'),
    path('Cdatetime/', views.Cdatetime, name='Cdatetime'),
    path('main/', views.main, name='main'),
    path('facture/',views.facture,name='facture'),
]

"""
Il faut maintenant indiquer au projet
le fichier de configuration de l'application
(modifier monProjet/urls.py)

"""

monProjet/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
   # path('polls/', include('polls.urls')), # on inclu la config url de poll/urls.py
    path('essai/', include('essai.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
# Pour associer une vue à une Url :
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

essai/models.py
from django.db import models

# Create your models here.
# si non spe dans la class la pk est un id autofield


class Etat(models.Model):
    # -> En Cours, En attente, Livré
    nomEtat = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nomEtat

class Types(models.Model):
    # -> Pdf, Papier, Mail,... etc
    nomTypes = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nomTypes

class Entreprise(models.Model):
    nomEntreprise = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nomEntreprise

class Societe(models.Model):
    entreprise = models.ForeignKey(Entreprise,on_delete=models.CASCADE)
    nomSociete = models.CharField(max_length=200)
   
    def __str__(self):
        return self.nomSociete

class Facture(models.Model):
    nomFacture =  models.CharField(max_length=200)
    societe = models.ForeignKey(Societe,on_delete=models.CASCADE)
    types = models.ForeignKey(Types,on_delete=models.CASCADE)
    etat = models.ForeignKey(Etat,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):#chaine de str
        return self.nomFacture

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime

# Create your models here.

# Les class Question et Choice herite de model
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

essai/views.py
from django.shortcuts import render

from django.http import HttpResponse,Http404
import datetime

from .models import Entreprise, Societe, Types, Etat, Facture
# On crée les vues ici

def index(request):
    """
    Lorsqu’une page est demandée, Django crée un objet HttpRequest
    qui contient des metadonnées, la vue doit lui renvoyer un objet
    HttpResponse 
    
    """
    return HttpResponse("Ceci est un index. <br> Mais aussi la vue la plus simple possible.")
   
    """
    Une fois la vue créé il convient de lassocier à une url
    Grâce à urls.py

    """

def facture(request):

    """
    # pb -> q.attribut , il ne prend pas la valeur de attribut mais son nom
    def lister(Class,attribut):
        class_list =Class.objects.order_by(attribut)
        output = ', '.join([q.attribut for q in class_list])
        res_list = [x for x in output.split(",")]
        return res_list
    """  
   
    #on recup le nom de l'entreprise qui a l'id 1
    nomEntreprise = Entreprise.objects.get(id=1)

    #on recup la liste des societe de cette entreprise
    nomSociete = Societe.objects.filter(entreprise__nomEntreprise__icontains=nomEntreprise)
    ok = list(nomSociete)


    # 1er graphique -> nombre de facture avec type


    # on recup la liste des types
    typesList = Types.objects.order_by('nomTypes')
    
    # on transforme en chaine de str séparé par ,
    output = ', '.join([q.nomTypes for q in typesList])

    # on slit grace , pour en faire une list (categorie = axe des x)
    categories = [x for x in output.split(",")]

    #on compte le nombre de facture par type envoyer en arg
    def nombreFact(x,y):
        return Facture.objects.filter(types__nomTypes__icontains=x).filter(societe__nomSociete__icontains=y).count()

    types=[]
    for x in categories:
        types.append(nombreFact(x.strip(),ok[0]))

    # axes des y + series
    donnee = [('Jouve',types)]

    # 2nd graphique -> categorie = chaque facture par heure avec -> etat
 
    etatList = Etat.objects.order_by('nomEtat')
    out = ', '.join([a.nomEtat for a in etatList])
    etat = [x for x in out.split(",")]

    def nombreFactE(x,y):
        return Facture.objects.filter(etat__nomEtat__icontains=x).filter(societe__nomSociete__icontains=y).count()

    state=[]
    for x in etat:
        state.append(nombreFactE(x.strip(),ok[0]))
        

    resEtat = [('Jouve',state)]

    return render(request, 'essai/facture.html', locals())


# test asynchrone :
async def Cdatetime(request):
    now = datetime.datetime.now()
    html = '<html><body>It is now %s.</body></html>' % now
    return HttpResponse(html)

# test boucle :
# Create your views here.
def main(request):
 
    categories = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    cities = [
    ('Tokyo', [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]),
    ('New York', [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]),
    ('London', [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]),
    ('Berlin', [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1])
    ]
    return render(request, 'essai/template.html', locals())

polls/views.py
# Create your views here.

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

essai/templates/essai/facture.html
<head>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>
<body>
     <p> Bienvenue sur le graphique de {{nomEntreprise|safe}} </p>
<div id='container'>
    <script>
      Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Facture par Types'
            },
             
            xAxis: {
                categories: {{categories|safe}},
                crosshair: true
            },

             series: [
            {% for donnee_name, donnee_data in donnee %}{
                name: '{{donnee_name}}',
                data: {{donnee_data|safe}}
 
            }
            {% if not forloop.last %},{% endif %}
            {% endfor %}]
            
        });

        
    </script>
</div>

<div id='etat'>
    <script>
      Highcharts.chart('etat', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Facture par Etat'
            },
             
            xAxis: {
                categories: {{etat|safe}},
                crosshair: true
            },

             series: [
            {% for resEtat_name, resEtat_data in resEtat %}{
                name: '{{resEtat_name}}',
                data: {{resEtat_data|safe}}
 
            }
            {% if not forloop.last %},{% endif %}
            {% endfor %}]
            
        });

        
    </script>
</div>

</body>

essai/templates/essai/template.html
<head>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>
<body>
     
<div id='container'>
    <script>
      Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Monthly Average Rainfall'
            },
             
            xAxis: {
                categories: {{categories|safe}},
                crosshair: true
            },
             
 
            series: [
            {% for city_name, city_data in cities %}{
                name: '{{city_name}}',
                data: {{city_data|safe}}
 
            }
            {% if not forloop.last %},{% endif %}
            {% endfor %}]
        });
    </script>
</div></body>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>